name: nebula_vault
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  photo_view: ^0.14.0
  image_picker: ^1.0.7
  path_provider: ^2.0.15
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  flutter_staggered_animations: ^1.1.0 # Para animaciones
  flutter_speed_dial: ^7.0.0
  intl: ^0.18.0
  video_thumbnail: ^0.5.3
  video_player: ^2.9.2
  transparent_image: ^2.0.0
  path: ^1.9.0
  mime: ^1.0.4
  android_intent_plus: ^3.0.0
  document_file_save_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
